// Centralized API abstraction for subscription management
import type { DbSubscription, Price, Product } from "@/types/subscription"; // Corrected import path
import { createSupabaseClient } from "@/lib/supabase";

export async function fetchSubscription(): Promise<DbSubscription | null> {
  try {
    // Use window.location.origin to get the current origin including protocol, hostname, and port
    const baseUrl = typeof window !== 'undefined' ? window.location.origin : '';
    const response = await fetch(`${baseUrl}/api/subscriptions`, {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
      },
    });

    if (!response.ok) {
      const errorData = await response.json();
      if (process.env.NODE_ENV !== 'production') {
        console.error("[fetchSubscription] API Error:", errorData);
      }
      throw new Error(
        errorData.error ||
          `Failed to fetch subscription: ${response.statusText}`,
      );
    }

    const data = await response.json();
    if (process.env.NODE_ENV !== 'production') {
      console.log("[fetchSubscription] Received data:", data);
    }
    return data.subscription as DbSubscription | null;
  } catch (error) {
    if (process.env.NODE_ENV !== 'production') {
      console.error("[fetchSubscription] Fetch Error:", error);
    }
    // Re-throw or handle as appropriate for the calling context (e.g., update state)
    throw error;
  }
}

export async function switchPlan(productId: string) {
  // TODO: Implement plan switching logic
}

export async function cancelSubscription() {
  // TODO: Implement cancellation logic
}

/**
 * Fetches the number of stories generated by the user in the current billing period.
 * Returns { used: 0 } on error for fail-safe UI, but logs error in dev for debugging.
 * @param userId - The user's ID
 * @param periodStart - ISO string for the start of the billing period
 * @param periodEnd - ISO string for the end of the billing period
 * @returns { used: number }
 */
export async function fetchStoryUsage(
  userId: string,
  periodStart?: string,
  periodEnd?: string,
): Promise<{ used: number }> {
  try {
    const supabase = createSupabaseClient();
    let query = supabase
      .from("stories")
      .select("id", { count: "exact", head: true })
      .eq("user_id", userId);
    if (periodStart) {
      query = query.gte("created_at", periodStart);
    }
    if (periodEnd) {
      query = query.lt("created_at", periodEnd);
    }
    const { count, error } = await query;
    if (error) throw error;
    return { used: count ?? 0 };
  } catch (err) {
    if (process.env.NODE_ENV !== 'production') {
      console.error("[fetchStoryUsage] Error:", err);
    }
    // Fail-safe: return 0 on error, but log for devs
    return { used: 0 };
  }
}

// Add more API functions as needed
