[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.8.1"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_WEBPACK_USEPOLLING = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[context.production.environment]
  NEXT_PUBLIC_SITE_URL = "https://stepintostorytime.netlify.app"

[context.deploy-preview.environment]
  NEXT_PUBLIC_SITE_URL = "https://deploy-preview-${REVIEW_ID}--stepintostorytime.netlify.app"

[context.branch-deploy.environment]
  NEXT_PUBLIC_SITE_URL = "https://${BRANCH}--stepintostorytime.netlify.app"

[functions]
  external_node_modules = ["@supabase/supabase-js"] 